/*Q 1 -Which actors have starred in the highest number of movies across all categories, and what is the total
revenue generated by those movies? */


SELECT a.first_name,a.last_name,a.actor_id, COUNT(*) AS film_count, SUM(f.rental_rate) AS revenue
FROM actor AS a
JOIN film_actor
ON a.actor_id = film_actor.actor_id
JOIN film AS f
ON film_actor.film_id = f.film_id
GROUP BY a.first_name,a.last_name,a.actor_id
ORDER BY film_count DESC
LIMIT 5